[package]
name = "advent-of-code"
version = "0.1.0"
edition = "2021"
default-run = "advent-of-code"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pico-args = "0.5.0"
